from __future__ import annotations


MOCK_ARTICLES: list[dict[str, object]] = [
    {
        "id": "clinic-waits-1",
        "source": "State Health Bulletin",
        "title": "Regional clinics report 12 percent drop in wait times this quarter",
        "summary": "The regional health agency published audited figures showing clinic wait times fell by roughly 12 percent after staffing changes.",
        "keywords": {"regional", "health", "agency", "clinic", "wait", "times", "12", "quarter", "audited"},
        "trust": 0.96,
        "stance": "supports",
        "topic": "clinic_wait_times",
    },
    {
        "id": "clinic-waits-2",
        "source": "University Public Health Review",
        "title": "Researchers validate reduced clinic delays in state report",
        "summary": "University researchers reviewed the same quarter data and confirmed lower clinic delays across the public network.",
        "keywords": {"researchers", "validate", "clinic", "delays", "state", "report", "quarter", "public"},
        "trust": 0.92,
        "stance": "supports",
        "topic": "clinic_wait_times",
    },
    {
        "id": "clinic-waits-3",
        "source": "Metro Desk",
        "title": "Hospital board says scheduling reform reduced waiting lines",
        "summary": "Hospital officials said scheduling reform helped reduce patient queues at several public clinics.",
        "keywords": {"hospital", "board", "scheduling", "reduced", "waiting", "public", "clinics"},
        "trust": 0.78,
        "stance": "supports",
        "topic": "clinic_wait_times",
    },
    {
        "id": "viral-rumor-1",
        "source": "Fact Ledger",
        "title": "No evidence for viral claim about hidden emergency report",
        "summary": "Fact-checkers found no public filing, agency memo, or credible witness supporting the rumor of a hidden emergency report.",
        "keywords": {"viral", "claim", "hidden", "report", "fact-checkers", "no", "evidence", "rumor"},
        "trust": 0.95,
        "stance": "contradicts",
        "topic": "hidden_report_rumor",
    },
    {
        "id": "viral-rumor-2",
        "source": "Civic Wire",
        "title": "Officials deny rumor of leaked internal bombshell",
        "summary": "Officials said the circulating posts misrepresent an old memo and no new leak has been verified.",
        "keywords": {"officials", "deny", "rumor", "leaked", "bombshell", "verified", "memo"},
        "trust": 0.88,
        "stance": "contradicts",
        "topic": "hidden_report_rumor",
    },
    {
        "id": "water-claim-1",
        "source": "Local Observer",
        "title": "Community group asks city for more water testing",
        "summary": "A neighborhood group requested more testing after residents reported unusual water taste, but no agency alert has been issued.",
        "keywords": {"community", "city", "water", "testing", "residents", "reported", "taste", "alert"},
        "trust": 0.58,
        "stance": "mentions",
        "topic": "water_quality_claim",
    },
    {
        "id": "water-claim-2",
        "source": "Utilities Update",
        "title": "Routine monitoring shows no citywide contamination alert",
        "summary": "Utility officials said routine monitoring has not triggered a citywide contamination notice.",
        "keywords": {"utility", "monitoring", "no", "contamination", "notice", "citywide", "officials"},
        "trust": 0.84,
        "stance": "contradicts",
        "topic": "water_quality_claim",
    },
]
